### ISSUE TITLE
Modal body [object HTMLDivElement] 

### ISSUE THREAD

**Issue by dhoko** [nico3333fr/van11y-accessible-modal-window-aria#1]
Hey,

cf [bug](https://twitter.com/dhoko_/status/854684992672280580)

* 1) Go => [demo modal](https://van11y.net/downloads/modal/demo/index-fr.html)
* 2) Click **Montre-moi une autre modale** or **C’est si facile**
* 3) Close the modal via ESC_KEY
* 4)  Click **Montre-moi une autre modale** or **C’est si facile**

### What is the expected result ?

![screenshot at 2017-04-19 15-20-47](https://cloud.githubusercontent.com/assets/713283/25182081/d0eddbda-2513-11e7-9ca5-a90dee976192.png)

### What happens instead ?

![screenshot at 2017-04-19 15-20-59](https://cloud.githubusercontent.com/assets/713283/25182085/d3b0b540-2513-11e7-81f0-0528a0bb515a.png)

the innerHTML of `#modal_id_2nd_example` changes:
![output](https://cloud.githubusercontent.com/assets/713283/25182284/6975f810-2514-11e7-88eb-fd1fb478c870.gif)

**Comment by nico3333fr** [comment]
Parfait, je viens de fixer dans https://github.com/nico3333fr/van11y-accessible-modal-window-aria/commit/da97f1b252e3dccbc7adee6e20df33502b948282 
Félicitation, vous venez de gagner une boisson offerte la prochaine fois qu'on se voit, pour avoir ouvert la première issue ! 👍 

![mask_coeur](https://cloud.githubusercontent.com/assets/2578321/25183700/9e4d1a24-2518-11e7-9efb-0f36f7a15adb.gif)


Closed #1

**Comment by dhoko** [comment]
![yeahhhh](https://cloud.githubusercontent.com/assets/713283/25183833/fdfe39b2-2518-11e7-9a26-d53a96922205.gif)
