### ISSUE TITLE
ability to add aria-describedby on the modal

### ISSUE THREAD

**Issue by ram1279** [nico3333fr/van11y-accessible-modal-window-aria#10]
Hello, I am are looking for the ability to provide aria-describedby on the modal. This establishes a relationship between dialog and text that described them. Additionally provides descriptive information about the dialog once defined.

**Comment by nico3333fr** [comment]
Hello,

the modal is already "described" by `aria-labelledby` attribute, which is pointing to the title in the modal. 

Is it what you require or do you need an option (for example a data attribute on the button, sort of `data-modal-describedby-id="here_your_id"` to add `aria-describedby="here_your_id"` to the modal?

**Comment by ram1279** [comment]
Yes, I am looking for an option that sets "aria-describedby" on the modal something like as you mentioned.

**Comment by nico3333fr** [comment]
Well, if the id is present in the page (the script will check that it exists)... why not? :)

I'll come back to you when it will be ready. Just have to check with my accessibility expert some points.

**Comment by nico3333fr** [comment]
Hi there,

finally, it was easy to fix, done in https://github.com/nico3333fr/van11y-accessible-modal-window-aria/commit/4b8e1982d816d5ba5f2b7985e4bd05c27d0328c2 

The 3rd example of the demo shows how it works: https://van11y.net/downloads/modal/demo/index.html

Cheers,
Nicolas
