### ISSUE TITLE
Open and close modal through javascript

### ISSUE THREAD

**Issue by ghost** [nico3333fr/van11y-accessible-modal-window-aria#14]
Hello,

I would like to open and close modal(s) through javascript. I mean without the user clicking on a specific button. My question is: is there something that looks like this: `open_modal('modal_id);`?
I have seen a previous question closed to this one but I think it was about detection which is not the point here.

And thank you for your plugin!

**Comment by RogerMoreno** [comment]
I resolve as follows:
I edited this code https://github.com/nico3333fr/van11y-accessible-modal-window-aria/blob/master/src/van11y-accessible-modal-window-aria.es6.js.
I changed the onLoad method of:
const onLoad = () => {
attach();
document.removeEventListener('DOMContentLoaded', onLoad);
}

for:
const onLoad = () => {
attach();
document.removeEventListener('DOMContentLoaded', onLoad);
let modalConfig = document.getElementById('openModal');
if (modalConfig) {
let setModal = {
backgroundEnabled: modalConfig.getAttribute('data-modal-content-id'),
modalCloseImgPath: modalConfig.getAttribute('data-modal-close-img'),
modalCloseText: modalConfig.getAttribute('data-modal-close-text'),
modalCloseTitle: modalConfig.getAttribute('data-modal-close-title'),
modalContentId: modalConfig.getAttribute('data-modal-content-id'),
modalDescribedById: modalConfig.getAttribute('data-modal-describedby-id'),
modalFocusBackId: modalConfig.getAttribute('data-focus-back'),
modalPrefixClass: modalConfig.getAttribute('data-modal-prefix-class'),
modalText: modalConfig.getAttribute('data-modal-text'),
modalTitle: modalConfig.getAttribute('data-modal-title')
};
openModal(setModal);
}
};

and include openModal:
let openModal = (setModal) => {
let body = doc.querySelector('body');

    body.insertAdjacentHTML('beforeEnd', createOverlay({
        backgroundEnabled: "",
        prefixClass: setModal.modalPrefixClass,
        text: setModal.modalCloseText
    }));

    // insert modal
    body.insertAdjacentHTML('beforeEnd', createModal(setModal));
};
If you insert an ID="openModal" with parameters the modal opens automatically:

```
<div id="openModal"
         data-modal-prefix-class="simple-animated-"
         data-modal-content-id="initial_modal_exec"
         data-modal-title="My automatic modal" 
         data-modal-text=""
         data-modal-close-text="Close"
         data-modal-close-title="Close"
         data-focus-back="klsadf" 
         data-modal-close-img="close.svg" 
         data-modal-describedby-id="">
        <div id="initial_modal_exec" class="hidden">
<p>Yeah, with <abbr title="Cascading Style Sheet">CSS</abbr> transforms, it is smoother.</p>
</div>
    </div>
[van11y-accessible-modal-window-aria.min_1530368048.zip](https://github.com/nico3333fr/van11y-accessible-modal-window-aria/files/3298149/van11y-accessible-modal-window-aria.min_1530368048.zip)

```
