### ISSUE TITLE
bug lorsque le button est composé d'une image

### ISSUE THREAD

**Issue by sbonaventure** [nico3333fr/van11y-accessible-modal-window-aria#2]
Lorsque le bouton est composé de HTML (une image dans mon cas), le script bug : 

```html
<button class="js-modal"><img src='[...]' alt='[...]' /><button>
```

Ce test renvoi ```false``` :
```js
hasClass(e.target, MODAL_JS_CLASS)
```

Et le script ne construit pas la modale

**Comment by nico3333fr** [comment]
Ah, je crois déjà avoir eu ce cas, je pense qu'il faut que je cherche dans l'événement voir si l'élément où il y a l'event est un enfant de MODAL_JS_CLASS. J'y regarde dès que possible.

**Comment by nico3333fr** [comment]
Yop, je viens d'envoyer un fix https://github.com/nico3333fr/van11y-accessible-modal-window-aria/commit/e50ca51ae57da1d11050f003d246ce30a82f64b3

Normalement, c'est bon, mais tu peux confirmer que ça roule de ton coté ?

**Comment by sbonaventure** [comment]
parfait, ça fonctionne !

**Comment by nico3333fr** [comment]
Tant mieux ! :)

On a bien mérité ça :
![fallon_dance](https://user-images.githubusercontent.com/2578321/28119010-a0b01568-6713-11e7-94f8-dbb88f870b1d.gif)

Merci bien pour avoir signalé le problème ;)

**Comment by sbonaventure** [comment]
<img src="https://media4.giphy.com/media/l2R0eYcNq9rJUsVAA/giphy.gif" alt="merci" />

**Comment by nico3333fr** [comment]
Hop, je t'ai mentionné ici du coup https://van11y.net/fr/2017/07/12/fix-pour-la-modale (et sur Twitter, toussa) ;)
