### ISSUE TITLE
Additional 'close' buttons

### ISSUE THREAD

**Issue by DidierLmn** [nico3333fr/van11y-accessible-modal-window-aria#3]
I use this plugin for a confirmation window, which has additional buttons to close/confirm an action.

After confirmation or cancellation I want to close the modal window, but I can't seem to find a way to this except for adding `id="js-modal-close"` to the buttons, but this is technically against the spec as there would be multiple elements with the same id.

So I was wondering if there's a class I can add (`class="js-modal-close"` doesn't work) to close the modal? Or if there's a function I can call to close the modal?

**Comment by nico3333fr** [comment]
Hi @DidierLmn 

the last commit has added this option : https://github.com/nico3333fr/van11y-accessible-modal-window-aria/commit/c2585cbea84d9b0c20017ea2ce1471b15d7f104e

The demo is updated with an example: https://van11y.net/downloads/modal/demo/index.html (see third example)

Merry Christmas ;)
Nico

**Comment by DidierLmn** [comment]
Hi Nico

Thanks for the quick follow up and implementation! :)

Happy holidays to you too
Didier
