### ISSUE TITLE
Invalid License Format

### ISSUE THREAD

**Issue by jmpresso** [nico3333fr/van11y-accessible-modal-window-aria#4]
The license is currently defined as follows:

```
 "license": [
    {
      "name": "MIT",
      "url": "https://github.com/nico3333fr/van11y-accessible-modal-window-aria/blob/master/LICENSE"
    }
  ]
```

Per [npm documentation](https://docs.npmjs.com/files/package.json), this is an old/invalid format for a license. It also breaks a standard license parser. Is it possible to correct this to a valid format?

**Comment by nico3333fr** [comment]
If I understand well, I jsut have to set it up like this: 

`"license": "MIT"`

to be ok ?

**Comment by nico3333fr** [comment]
Hi @jmpresso 

it has been fixed in last commit https://github.com/nico3333fr/van11y-accessible-modal-window-aria/commit/89b2d2ecb13b2a15d697de427ec85b7a2b12c42b 

Thanks for pointing this out 👍

**Comment by jmpresso** [comment]
@nico3333fr - Perfect, thanks!

**Comment by nico3333fr** [comment]
@jmpresso I've fixed it for all Van11y's projects ;) Thanks again.
