### ISSUE TITLE
Dépassement du viewport

### ISSUE THREAD

**Issue by nicolasbocquet** [nico3333fr/van11y-accessible-modal-window-aria#5]
Bonjour,

J'ai une suggestion à proposer pour éviter ce cas :

Sur la page https://van11y.net/downloads/modal/demo/index.html :
![modal](https://user-images.githubusercontent.com/3034108/34904053-db48f850-f83d-11e7-860a-37a10e7d5a5b.png)

`.simple-modal, .simple-animated-modal {
  top: 5vh;
  max-height: 90vh;
}`

**Comment by nico3333fr** [comment]
Yop,

merci pour l'idée. J'avais déjà un `max-height: 98vh`, faudrait voir si les vh pourraient marcher partout, y compris sur iPhone/etc. Tu as testé sur d'autres navigateurs ?

**Comment by nicolasbocquet** [comment]
Pas de soucis sur iPhone, tu avais déjà prévu un width / height de 98%. ;)

**Comment by nico3333fr** [comment]
Voilà, c'est amélioré dans le dernier commit https://github.com/nico3333fr/van11y-accessible-modal-window-aria/commit/1a7b13504b1a76b7eb25cb88b23b4c2ecadf816e ;)

Merci et au plaisir 👍
