### ISSUE TITLE
Cannot specify initial focus

### ISSUE THREAD

**Issue by codemusket** [nico3333fr/van11y-accessible-modal-window-aria#6]
https://github.com/nico3333fr/van11y-accessible-modal-window-aria/blob/3dac138593cf982d15996a5f41449e2169e86680/dist/van11y-accessible-modal-window-aria.js#L270

Hello, I would like to request the ability to specify an initial focus. I actually need it to be able to focus on the entire layer initially, then tab loop inside the modal as currently does. The problem is screen readers read the X button first, which isn't the intent. We want to ensure that the message is read out first, then the user can cycle between content button and X button.

**Comment by nico3333fr** [comment]
I'm working on adding a data-attribute to an id.

**Comment by nico3333fr** [comment]
Hi @codemusket 

it is added in https://github.com/nico3333fr/van11y-accessible-modal-window-aria/commit/292f38070b412751af9ce883627b8cb27474ccf2 

I've updated the readme, and examples. 

Cheers,
Nicolas
